### PR TITLE
Tabs improvements

### PR DESCRIPTION
**Pull request by AndroMaster436**
Added switching to a new tab after opening a file and added animation for switching between tabs

### CODE REVIEW

**Comment by AndroMaster436** [comment]
> Just remove the whole line viewPager.setCurrentItem(tab!!.position, true)

If I remove whole line, then the switching won't work at all. Or did I get it wrong?

**Comment by RohitKushvaha01** [comment]
> > Just remove the whole line viewPager.setCurrentItem(tab!!.position, true)
> 
> If I remove whole line, then the switching won't work at all. Or did I get it wrong?

Not a big deal

**Comment by AndroMaster436** [comment]
> > > Just remove the whole line viewPager.setCurrentItem(tab!!.position, true)
> > 
> > 
> > If I remove whole line, then the switching won't work at all. Or did I get it wrong?
> 
> Not a big deal

Deleted
https://github.com/AndroMaster436/Xed-Editor/commit/5726cc054b4ec3fb2df3b7028772ec1262083242

**Comment by AndroMaster436** [comment]
> > > > Just remove the whole line viewPager.setCurrentItem(tab!!.position, true)
> > > 
> > > 
> > > If I remove whole line, then the switching won't work at all. Or did I get it wrong?
> > 
> > 
> > Not a big deal
> 
> Deleted [AndroMaster436@5726cc0](https://github.com/AndroMaster436/Xed-Editor/commit/5726cc054b4ec3fb2df3b7028772ec1262083242)

But now it doesn't compile

**Pull request merged**
